name: Kontrol

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests cloudscraper beautifulsoup4

      - name: inn.py
        continue-on-error: true
        run: python inn.py

      - name: an.py
        continue-on-error: true
        run: python an.py

      - name: selcuk.py
        continue-on-error: true
        run: python selcuk.py

      - name: r.py
        continue-on-error: true
        run: python r.py

      - name: r2.py
        continue-on-error: true
        run: python r2.py

      - name: ftb.py
        continue-on-error: true
        run: python ftb.py

      - name: birlestir.py
        continue-on-error: true
        run: python birlestir.py

      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: diff
        run: |
          git diff --quiet || echo "var=true" >> $GITHUB_OUTPUT

      - name: Commit & FORCE Push (KESÄ°N)
        if: steps.diff.outputs.var == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ðŸ”„ Otomatik M3U gÃ¼ncelleme" || exit 0
          git push --force
