name: NeonSpor M3U8

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-neon:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run NeonSpor scraper
        run: |
          python3 neonspor.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update neonspor.m3u8"
          file_pattern: neonspor.m3u8
